apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: evgeniyp92/simpleapi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
              protocol: TCP
      restartPolicy: Always
      